version: "3"

services:
  dynamodb-local:
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    hostname: dynamodb-local
    volumes:
      - ./dynamo:/home/dynamodblocal/data