version: '3'

services:
    backend:
        build: ./backend
        depends_on:
            - db-setup
        environment:
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=not-specified-not-needed
            - AWS_SECRET_ACCESS_KEY=not-specified-not-needed
            - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
        ports:
            - '4000:4000'
        volumes:
          - './backend:/app'
    dynamodb-local:
        command:
            [
                '-jar',
                'DynamoDBLocal.jar',
                '-sharedDb',
                '-dbPath',
                '/home/dynamodblocal/data',
            ]
        container_name: dynamodb-local
        image: amazon/dynamodb-local
        ports:
            - '8000:8000'
        hostname: dynamodb-local
        volumes:
            - ./dynamo:/home/dynamodblocal/data
    frontend:
        build: ./frontend
        ports:
            - '7328:3000'
        stdin_open: true
        volumes:
          - './frontend:/app'
    web:
        image: nginx
        ports:
            - '7327:80'
        # volumes:
        #   - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
        command: [nginx-debug, '-g', 'daemon off;']
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
    db-setup:
        image: amazon/aws-cli
        environment:
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=not-specified-not-needed
            - AWS_SECRET_ACCESS_KEY=not-specified-not-needed
        volumes:
            - ./wait-for-it:/scripts
        entrypoint: bash
        command:
            [
                '/scripts/wait-for-it.sh',
                'dynamodb-local:8000',
                '--',
                'aws',
                'dynamodb',
                'create-table',
                '--table-name',
                'Games',
                '--attribute-definitions',
                'AttributeName=PK,AttributeType=S',
                'AttributeName=SK,AttributeType=S',
                '--key-schema',
                'AttributeName=PK,KeyType=HASH',
                'AttributeName=SK,KeyType=RANGE',
                '--billing-mode',
                'PAY_PER_REQUEST',
                '--endpoint-url',
                'http://dynamodb-local:8000',
            ]
        depends_on:
            - dynamodb-local
    am:
        command: tail -F /dev/null
        entrypoint: tail
        environment:
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=not-specified-not-needed
            - AWS_SECRET_ACCESS_KEY=not-specified-not-needed
        image: amazon/aws-cli
